### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by instax-dutta** [Luxxy-GF/pterodactyl-bot#2]
C:\Users\intel\Downloads\pterodactyl-bot-master\pterodactyl-bot-master\node_modules\discord.js\src\rest\RequestHandler.js:350
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Missing Access
    at RequestHandler.execute (C:\Users\intel\Downloads\pterodactyl-bot-master\pterodactyl-bot-master\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\intel\Downloads\pterodactyl-bot-master\pterodactyl-bot-master\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async GuildApplicationCommandManager.set (C:\Users\intel\Downloads\pterodactyl-bot-master\pterodactyl-bot-master\node_modules\discord.js\src\managers\ApplicationCommandManager.js:146:18)        
    at async Client.<anonymous> (C:\Users\intel\Downloads\pterodactyl-bot-master\pterodactyl-bot-master\handler\index.js:53:9) {
  method: 'put',
  path: '/applications/916229869443092531/guilds/972381575469748234/commands',
  code: 50001,
  httpStatus: 403,
  requestData: { json: [], files: [] }
}

**Comment by DasEntlein01** [comment]
Give your Bot Perms
